### PR TITLE
Video upload

### PR DESCRIPTION
**Pull request by fitnr**
As I mentioned in #655, this is an alternate way of adding video upload. The media_upload method gets a conditional, with smaller images routed to 'normal' upload, and larger images and videos chunked upload. I also moved upload limits to a class variable, to make them easier to change if the need arises.

This also fixes from unicode errors as flagged by @jeremylow.

### CODE REVIEW

**Comment by fitnr** [comment]
It's been a year and a half, but it would still be great to have video upload in production Tweepy. I've been using this branch for an application with no problems in that time.

**Comment by jmartone** [comment]
Did Twitter change something in the API, because I get the following error when uploading a 14mb GIF:

```Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".../tweepy/api.py", line 267, in upload_chunked
  File ".../tweepy/binder.py", line 258, in _call
  File ".../tweepy/binder.py", line 242, in execute
  tweepy.error.TweepError: File size exceeds 5242880 bytes.

**Comment by jamiewinspear** [comment]
@fitnr Hi fitnr, I have been testing this branch for use in our production application and it looks great! Thanks for writing it. I was wondering if this is the most recent version of this code, and if there was anything I can do to help you get this merged to tweepy proper? I was intending on opening a new PR with these exact code if this doesn't get a response in the next couple of days, I hope that is ok with you.

**Comment by fitnr** [comment]
@jamiewinspear Glad it's useful for you. I don't know if there's a way to get it merged. I doubt an additional pull would do much, I don't want to put too much on @Aaron1011's plate.

**Comment by jamesandres** [comment]
Hi @fitnr, I work with @jamiewinspear, we are actually testing your branch video_upload2 on your local fork (ie: not the branch linked to this PR). Fyi, we have also crafted a fix for the issue @jmartone raised (the commit is in a local repo at the moment, when it's ready we'll post a link).

From our perspective, we need chunked upload functionality available in tweepy and are happy to help get it reviewed, tested, merged. Very much want to avoid running a fork of tweepy just to get this functionality.

A few questions for you, if you don't mind:
1. Are you using your video_upload2 branch in production?
2. Are you planning to make a PR using video_upload2?
3. How can we help?

Thanks,

**Comment by fitnr** [comment]
1. Yes, I've been using it in production painlessly for a few years now.
2. I wasn't planning on making a pull request. The only difference between `video_upload` and `video_upload2` is that the latter has been rebased to take advantage of newer commits in this repo. It was a pain, so I understand your desire not to run off a fork!
3. It sounds like you have the best current version of the functionality, so why don't you submit a new pull request? If you mention me in it, and I'll close this one when I see it. (Perhaps you can base your pull request off of `video_upload2`, which will keep the history a bit tidier.)

**Comment by jamesandres** [comment]
Hi @fitnr have created a PR from your video_upload2 over here https://github.com/tweepy/tweepy/pull/929 and applied our little fix for media_category on top.

**Comment by fitnr** [comment]
Closing in favor of #929.

**Comment by braian87b** [comment]
Is there a way to upload a video or not?

**Comment by Harmon758** [comment]
@braian87b As said, this PR was closed in favor of #929.

**Comment by Harmon758** [comment]
The video-upload branch / pull request #1486 should be complete now.
Any feedback or review would be appreciated.

**Pull request closed without merging**
