### PR TITLE
Make tweepy compatible with Python 3.3

### PR DESCRIPTION
**Pull request by judy2k**
Major points are (as far as I can remember):
- Updated dependencies to more recent versions.
- Moved testing to tox.
- Passing test_api and test_utils tests (other tests _probably_ failing - I can look at them if you'd like - I notice some are failing under Python 2 anyway).
- Calls to bound endpoints are no longer passing in self - this was causing self to be passed in as an http param.

### CODE REVIEW

**Comment by DarkRedman** [comment]
Since there are many issues recently having errors when using tweepy even after hours of pause before retrying (ratelimit) it does not work so I wanted to clone git the repo locally and launched the tests but I have repeated import errors !

```EEEEEE..
======================================================================
ERROR: test_api (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_api
Traceback (most recent call last):
  File "/usr/lib/python3.7/unittest/loader.py", line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File "/usr/lib/python3.7/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/home/user/tweepy/tests/test_api.py", line 8, in <module>
    from .config import tape, TweepyTestCase, use_replay, username
ImportError: attempted relative import with no known parent package


======================================================================
ERROR: test_auth (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_auth
Traceback (most recent call last):
  File "/usr/lib/python3.7/unittest/loader.py", line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File "/usr/lib/python3.7/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/home/user/tweepy/tests/test_auth.py", line 8, in <module>
    from .config import *
ImportError: attempted relative import with no known parent package


======================================================================
ERROR: test_cursors (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_cursors
Traceback (most recent call last):
  File "/usr/lib/python3.7/unittest/loader.py", line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File "/usr/lib/python3.7/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/home/user/tweepy/tests/test_cursors.py", line 1, in <module>
    from .config import tape, TweepyTestCase, username
ImportError: attempted relative import with no known parent package


======================================================================
ERROR: test_rate_limit (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_rate_limit
Traceback (most recent call last):
  File "/usr/lib/python3.7/unittest/loader.py", line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File "/usr/lib/python3.7/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/home/user/tweepy/tests/test_rate_limit.py", line 4, in <module>
    from .config import create_auth
ImportError: attempted relative import with no known parent package


======================================================================
ERROR: test_resultset (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_resultset
Traceback (most recent call last):
  File "/usr/lib/python3.7/unittest/loader.py", line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File "/usr/lib/python3.7/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/home/user/tweepy/tests/test_resultset.py", line 1, in <module>
    from .config import TweepyTestCase
ImportError: attempted relative import with no known parent package


======================================================================
ERROR: test_streaming (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_streaming
Traceback (most recent call last):
  File "/usr/lib/python3.7/unittest/loader.py", line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File "/usr/lib/python3.7/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/home/user/tweepy/tests/test_streaming.py", line 9, in <module>
    from .config import create_auth
ImportError: attempted relative import with no known parent package


----------------------------------------------------------------------
Ran 8 tests in 0.001s

FAILED (errors=6)```

**Comment by Harmon758** [comment]
Please don't necrobump issues/PRs.
This also has absolutely nothing to do with this PR.
As the error says, it's unable to find the parent package because you're not in the root directory of the repository when running tests.
See https://tweepy.readthedocs.io/en/latest/running_tests.html.

**Comment by DarkRedman** [comment]
Excuse me ?! First of I didn't post on an issue with that title, but it was about a bug on RateLimits, secondly, if you don't want people to "Necrobump" as you say an issue, start by fixing thoses, duh and yes I was in the root directory when I did it !

**Comment by Harmon758** [comment]
> I didn't post on an issue with that title

Not sure what title you're referring to, but yes, you're commenting on a 5-year-old PR that has nothing to do with issues with rate limits or tests.
> it was about a bug on RateLimits

Again, I'm not sure what you're referring to, but feel free to create a new issue if you have a bug to report that doesn't have an open issue already.
> start by fixing thoses

As the previous comments outlined, this PR was superseded by another which added support for Python 3.3 resolving any issues in that respect. Regardless, Python 3.3 has been EOL for more than two years and Tweepy no longer supports it anyways.
> I was in the root directory when I did it

That doesn't make much sense since those errors are saying that the tests were unable to find the parent package that would be in the directory you're running the tests from.
Feel free to create a new issue if you have a reproducible example (MCVE/SSCCE) or steps for what you're trying.

**Pull request closed without merging**
