### PR TITLE
Test case for PR #635 (and bug #615) 

### PR DESCRIPTION
**Pull request by wjt**
There was already a test case for `ReadBuffer` but it wasn't run and was broken anyway, so bug #615 was not caught.

Here's a patch on top of @varzac's fix on #635 which tests that fix. Passes under 2.7 and 3.4, at least.

### CODE REVIEW

**Comment by varzac** [comment]
Thanks for the assist @wjt!  My PR has been open for a while with no response, but maybe with your tests they will consider it.

**Comment by wjt** [comment]
@varzac no problem! Part-way through writing a similar patch, it was nice to find you'd done the hard work :smiley:

**Comment by wjt** [comment]
Dear maintainers: merging this PR would resolve #615, #635, #652, #616. Anything I can do to help with the maintenance burden?

**Comment by joshthecoder** [comment]
Looks good. Sorry for the delay, had little time to keep on top of PRs and issues.

**Comment by wjt** [comment]
@joshthecoder no problem – LMK if there's some way I can help with the load. BTW you might like to close those other PRs for this bug, just to help keep the pile of PRs under control!

**Pull request merged**
