### PR TITLE
Account Activity API implementation

### PR DESCRIPTION
**Pull request by bpluly**
Support Account Activity API #1075[https://github.com/tweepy/tweepy/issues/1075](url)

The __version__ in __init__.py has NOT been bumped. only the reference to activityAPI.ActivityAPI

### CODE REVIEW

**Comment by JohnnyZ** [comment]
What is holding this back from getting merged in? I feel this would be quite useful to a large number of the users of tweepy.

**Comment by bpluly** [comment]
> 
> 
> What is holding this back from getting merged in? I feel this would be quite useful to a large number of the users of tweepy.

I don't know of a particular reason, it has not yet been reviewed. I picked on three people, :-) they may have 3 entirely different reasons. It isn't a small piece of code and whilst I have it in use every day without any current issues that doesn't mean there aren't any.

It does need a test suite.

**Comment by aadhavksuresh** [comment]
@bpluly Hey there. I am trying to use your code. I would appreciate some help if you could contact me on Discord. SirRomey#0001.

**Comment by bpluly** [comment]
I can tomorrow.

**Comment by aadhavksuresh** [comment]
That'd be great. Thanks a lot.

**Comment by bpluly** [comment]
> 
> 
> That'd be great. Thanks a lot.

You'll have to add me. bpluly#2029

**Comment by bpluly** [comment]
Added Developer/User Tutorial #1381

**Comment by Harmon758** [comment]
This PR has been stale for a while now, but it is decidedly so now that [the Premium v1.1 Account Activity API has been deprecated](https://twittercommunity.com/t/deprecating-the-premium-v1-1-api/191092).

**Pull request closed without merging**
