### PR TITLE
Add model for streaming events

### PR DESCRIPTION
**Pull request by wjt**
I've been using something like this by overriding `on_data` in my application to handle favourite/RT/follow events, and it works fine there. I've tested this branch locally (manually), and added a very cursory case to the test suite.

### CODE REVIEW

**Comment by wjt** [comment]
Rebased, with support and a test for the `quoted_tweet` event added since I first submitted this PR.

**Comment by wjt** [comment]
Rebased again, nothing needed changing.

**Comment by wjt** [comment]
Time for the annual ceremonial rebase!

**Comment by Harmon758** [comment]
This PR is stale now, since it seems to be for User Streams, which have been deprecated and retired in favor of the new Account Activity API.
For Account Activity API support, see #1075.

Also see:
https://developer.twitter.com/en/docs/accounts-and-users/subscribe-account-activity/migration/us-ss-migration-guide.html

https://blog.twitter.com/developer/en_us/topics/tools/2018/enabling-all-developers-to-build-on-the-account-activity-api.html
https://blog.twitter.com/developer/en_us/topics/tools/2017/announcing-more-functionality-to-improve-customer-engagements-on-twitter.html
https://blog.twitter.com/developer/en_us/topics/tools/2017/building-the-future-of-the-twitter-api-platform.html

https://twittercommunity.com/t/details-and-what-to-expect-from-the-api-deprecations-this-week-on-august-16-2018/110746
https://twittercommunity.com/t/reminder-site-streams-user-streams-and-legacy-dm-endpoints-will-be-sunset-august-16th/109482
https://twittercommunity.com/t/building-on-site-streams-user-streams-or-direct-messages-action-required-to-preserve-and-prevent-disruption-to-your-twitter-integration/105736
https://twittercommunity.com/t/date-for-full-deprecation-of-user-streams-site-streams-and-legacy-direct-message-api-endpoints/98734

**Pull request closed without merging**
