### PR TITLE
Fix cache

### PR DESCRIPTION
**Pull request by DarkRedman**
Fixing the cache key for both get and store methods

### CODE REVIEW

**Comment by DarkRedman** [comment]
Apparently there is an error there.
`testcachedresult (tests.test_api.TweepyAPITests) ... ERROR`

But I can't see the test code and there is not explanation about the error.

**Comment by DarkRedman** [comment]
I don't understand why the cache patch has been ignore again ? Each time there is an update it's broken.

**Comment by DarkRedman** [comment]
I let it there in case you plan to patch it again.

```diff
10c10
< from six.moves.urllib.parse import quote
---
> from six.moves.urllib.parse import quote, urlencode
135c135
<                 cache_result = self.api.cache.get(url)
---
>                 cache_result = self.api.cache.get('%s?%s' % (url, urlencode(self.session.params)))
236c236
<                 self.api.cache.store(url, result)
---
>                 self.api.cache.store('%s?%s' % (url, urlencode(self.session.params)), result)
```

**Comment by Harmon758** [comment]
I'm not sure what you mean.
This PR was merged and has been released as part of v3.6.0.

**Comment by DarkRedman** [comment]
This is an old post.

**Comment by Harmon758** [comment]
This PR was merged months before your comments.

**Pull request merged**
