### PR TITLE
Allow optionally setting daemon flag on async threads.

### PR DESCRIPTION
**Pull request by mmontagna**
Would you be open to a PR which sets the daemon flag on async threads?

https://docs.python.org/3/library/threading.html#threading.Thread.daemon

This will allow python scripts to exit cleanly when all non-daemon threads are stopped. The current behavior is that the streaming thread stays up and prevents the script from exiting.

[EDIT]
Changed PR to optionally allow setting daemon flag, but maintain the default behavior of setting it to false.

### CODE REVIEW

**Comment by mmontagna** [comment]
Ahh I see this PR already existed: https://github.com/tweepy/tweepy/pull/268

**Comment by mmontagna** [comment]
Ahh I see this PR already existed: https://github.com/tweepy/tweepy/pull/268

**Comment by mmontagna** [comment]
What if it was added as an option which could be passed to the functions which start async threads?

**Comment by joshthecoder** [comment]
Yeah I think adding this as an option makes sense. How about we pass it to the "options" object the constructor receives? Then you can just assign it to `self` like we do for the other options (default is false).

**Comment by mmontagna** [comment]
@joshthecoder Alright I've updated the PR to make it an option to the Stream constructor. What do you think now?

Also are there any docs I should update?

**Comment by joshthecoder** [comment]
Looks good now thanks! Sorry for the long wait on seeing this again

**Pull request merged**
