### PR TITLE
Treat IncompleteRead as a disconnect or timeout, and reconnect.

### PR DESCRIPTION
**Pull request by tewalds**
Fix for #18, #92, #237, #242, #448.

### CODE REVIEW

**Comment by vbmade2000** [comment]
I installed latest version from tweepy but I am still getting IncompleteRead(0 bytes read, 287 more expected)', IncompleteRead(0 bytes read, 287 more expected))

**Comment by gambolputty** [comment]
Me too! 

`ProtocolError: ('Connection broken: IncompleteRead(0 bytes read, 3346 more expected)', IncompleteRead(0 bytes read, 3346 more expected))`

**Comment by Andergraw** [comment]
I'm having the same problem with Tweepy 3.5.0

**Comment by lluisrojass** [comment]
yeah, just encountered this issue yesterday. Any news or updates on this?

**Comment by nishchit** [comment]
Bug still exists

**Comment by venkat1017** [comment]
can you try pip install tweepy --upgrade this worked for me

**Comment by Harmon758** [comment]
This fix seems to have been reverted with https://github.com/tweepy/tweepy/commit/34af675c8e24b5176dae276342126fb52816ae6e, due to https://github.com/tweepy/tweepy/issues/501. See #237.

**Comment by ehernandezvilla** [comment]
I'm having the same problem with the last version!

**Pull request merged**
