### PR TITLE
PageIterator: Change initial page number to 1 and handled duplicates

### PR DESCRIPTION
**Pull request by manji369**
Initialized self.current_page to 1 instead of 0 and handled duplicates from previous pages to return unique results and to determine the stop iteration criteria (Refer issue [958](https://github.com/tweepy/tweepy/issues/958)).

### CODE REVIEW

**Comment by TimotheeJeannin** [comment]
Is this going to me merged soon ?

**Comment by jaredthecoder** [comment]
@Harmon758 I am going to test these changes locally with search_users() and I'll let you all know if it still works.

**Comment by jaredthecoder** [comment]
Screen Shot 2019-10-18 at 11 26 53

Seems to be working.

**Comment by meow232309** [comment]
Hi,
So i'm still seeing the same issue here and don't believe its fixed. Anyone else having issues?

thanks

**Comment by meow232309** [comment]
> Screen Shot 2019-10-18 at 11 26 53
> 
> Seems to be working.

I just did the same thing with a different query for page 1 and 2 and got the exact same results.

**Review by Harmon758 — CHANGES_REQUESTED** [review]
This should fix two separate bugs (#958). The first being simply the initial page number incorrectly being 0 instead of 1, and the second being [a longstanding issue with Twitter's API that won't be fixed before a Twitter API v2 equivalent endpoint is released](https://twittercommunity.com/t/odd-pagination-behavior-with-get-users-search/148502) (#1465).

I think the [GET users/search endpoint](https://developer.twitter.com/en/docs/twitter-api/v1/accounts-and-users/follow-search-get-users/api-reference/get-users-search) is the last remaining endpoint to still use the `page` parameter, so since the `PageIterator` will likely only be used for [`API.search_users`](https://tweepy.readthedocs.io/en/latest/api.html#API.search_users), there shouldn't be any performance impacts on using a `Cursor` with any other methods due to any implementation that fixes the latter bug, even if the GET users/search endpoint is the only one that exhibits it.

Since the latter bug causes identical pages after the last, removing duplicates and using a flag to raise `StopIteration` on the page after shouldn't be necessary, as it would just return an extra empty page. `StopIteration` can just be raised immediately when duplicates are encountered. This should also remove the need for a `temp_items`.

Using two sets of IDs also shouldn't be necessary, as the current list of items/users can simply be compared with the previous one.

There are also conflicts that need to be resolved now.

**Comment by Harmon758** [comment]
@meow232309 Are you using the version in this PR?

**Comment by Harmon758** [comment]
This should now be resolved by https://github.com/tweepy/tweepy/commit/a7d1608903825a4c2d781e5f8f709f26ed1bad03 and https://github.com/tweepy/tweepy/commit/3c1a397cd8d5bb81ff245ca0645c6462e57a5d33.

**Pull request closed without merging**
