### PR TITLE
Support Twitter API v2

### PR DESCRIPTION
**Pull request by Harmon758**
This pull request adds support for Twitter API v2, resolving parts of #1472, with a `Client` class and its methods:

- `Client.hide_reply` ([PUT /2/tweets/:id/hidden](https://developer.twitter.com/en/docs/twitter-api/tweets/hide-replies/api-reference/put-tweets-id-hidden))
- `Client.unhide_reply` ([PUT /2/tweets/:id/hidden](https://developer.twitter.com/en/docs/twitter-api/tweets/hide-replies/api-reference/put-tweets-id-hidden))
- `Client.search_all_tweets` ([GET /2/tweets/search/all](https://developer.twitter.com/en/docs/twitter-api/tweets/full-archive-search/api-reference/get-tweets-search-all))
- `Client.search_recent_tweets` ([GET /2/tweets/search/recent](https://developer.twitter.com/en/docs/twitter-api/tweets/search/api-reference/get-tweets-search-recent))
- `Client.get_users_mentions` ([GET /2/users/:id/mentions](https://developer.twitter.com/en/docs/twitter-api/tweets/timelines/api-reference/get-users-id-mentions))
- `Client.get_users_tweets` ([GET /2/users/:id/tweets](https://developer.twitter.com/en/docs/twitter-api/tweets/timelines/api-reference/get-users-id-tweets))
- `Client.get_tweet` ([GET /2/tweets](https://developer.twitter.com/en/docs/twitter-api/tweets/lookup/api-reference/get-tweets))
- `Client.get_tweets` ([GET /2/tweets/:id](https://developer.twitter.com/en/docs/twitter-api/tweets/lookup/api-reference/get-tweets-id))
- `Client.unfollow` ([DELETE /2/users/:source_user_id/following/:target_user_id](https://developer.twitter.com/en/docs/twitter-api/users/follows/api-reference/delete-users-source_id-following))
- `Client.get_users_followers` ([GET /2/users/:id/followers](https://developer.twitter.com/en/docs/twitter-api/users/follows/api-reference/get-users-id-followers))
- `Client.get_users_following` ([GET /2/users/:id/following](https://developer.twitter.com/en/docs/twitter-api/users/follows/api-reference/get-users-id-following))
- `Client.follow` ([POST /2/users/:id/following](https://developer.twitter.com/en/docs/twitter-api/users/follows/api-reference/post-users-source_user_id-following))
- `Client.get_user` ([GET /2/users/:id](https://developer.twitter.com/en/docs/twitter-api/users/lookup/api-reference/get-users-id), [GET /2/users/by/username/:username](https://developer.twitter.com/en/docs/twitter-api/users/lookup/api-reference/get-users-by-username-username))
- `Client.get_users` ([GET /2/users](https://developer.twitter.com/en/docs/twitter-api/users/lookup/api-reference/get-users), [GET /2/users/by](https://developer.twitter.com/en/docs/twitter-api/users/lookup/api-reference/get-users-by))

New API v2 models have been added:

- `Media`
- `Place`
- `Poll`
- `ReferencedTweet`
- `Tweet`
- `User`

replacing API v1.1 models (which can still be accessed through `tweepy.models`) in the package namespace.

A `Paginator` has also been added for use with `Client` methods.

This PR also includes documentation and tests for `Client`, as well as documentation for `Paginator` and the new models.

~~Currently, this is in a very preliminary rough draft state, and many parts of this initial implementation might change before this pull request is complete. I wanted to get this branch and draft pull request out as soon as possible, as there have been requests to do so (e.g. by @sparack and others) and so that anyone can test Twitter API v2 and provide feedback on Tweepy's interface for it.~~

~~Note, there is still planned functionality missing in this initial implementation, such as error and rate limit handling, a pagination interface, and methods for the newest manage follows endpoints.
Documentation and tests also have not been added yet.
I'm also still considering how to expose `tweepy.user.User`, so as not to conflict with the API v1.1 `User` object/model.~~

### CODE REVIEW

**Comment by sarim-zafar** [comment]
Any update on this?

**Comment by azharmunir43** [comment]
hey @Harmon758, thanks for this, I was going through client.py file and had a look a below methods: -

image

Shouldn't we provide user_auth parameter for these methods upfront because whether or not to use OAuth1, depends upon the metrics we are requesting? I mean if we are requesting public metrics only, Bearer authorization should suffice but if we are requesting non_pubilc metrics as well, we are supposed to use Auth handler.

I am just a newbie trying to be helpful, so apologies if I am missing something

**Comment by Harmon758** [comment]
Yeah, that's one of the last remaining TODOs:
https://github.com/tweepy/tweepy/blob/f4ca48788c5912e4db32d02e0b839282d8d586b5/tweepy/client.py#L71
I'm still deciding on a design for the implementation.
Thanks for the feedback though.

**Comment by Harmon758** [comment]
This branch/pull request should be complete now.
I plan on adding methods for the new Follows and Blocks endpoints (see #1472) after this has been merged.
Streaming will probably be a separate PR.

Any feedback and/or review from @sparack or anyone else would be appreciated.

**Pull request merged**
