### PR TITLE
Added the function create_mute and destroy_mute

### PR DESCRIPTION
**Pull request by antoinemcgrath**
Per request and my own needs this the ability to mute and unmute was added.

Further details on the Twitter API POST actions:

create_mute()
https://developer.twitter.com/en/docs/accounts-and-users/mute-block-report-users/api-reference/post-mutes-users-create

destroy_mute()
https://developer.twitter.com/en/docs/accounts-and-users/mute-block-report-users/api-reference/post-mutes-users-destroy

### CODE REVIEW

**Comment by ZiyadMoraished** [comment]
How about adding one more function to mute a list of users at once 

```
     @property
     def mutes_ids(self):
         """ :reference: https://dev.twitter.com/rest/reference/get/mutes/users/ids """
         return bind_api(
             api=self,
             path='/mutes/users/ids.json',
             payload_type='json',
             require_auth=True
```

**Comment by oanceamax** [comment]
Hello I'm trying to mute people that follow me with Tweepy but i get the error "AttributeError: 'User' object has no attribute 'create_mute'" I'm new to coding in Python but i would appreciate your help. Thanks a lot

**Comment by oanceamax** [comment]
> As you can see from this merged PR, `create_mute` is a class method for `API`, not for the `User` object.

I have managed to fire it out. Still trying to get the hang of this.  Thanks

**Comment by oanceamax** [comment]
> As you can see from this merged PR, `create_mute` is a class method for `API`, not for the `User` object.

Can use the **create_mute** method in this code ?

`auth = tweepy.OAuthHandler(CONSUMER_KEY, CONSUMER_SECRET)
auth.set_access_token(ACCESS_TOKEN, ACCESS_TOKEN_SECRET)
api = tweepy.API(auth)
 
for follower in tweepy.Cursor(api.followers).items(10):
    follower.follow()
    print (follower.screen_name)`

**Comment by Harmon758** [comment]
I'm not sure what you're asking.
You set `api` as an instance of `tweepy.API`, so yes, you can just use `api.create_mute`.

**Comment by oanceamax** [comment]
I get this : 'API'** object has no attribute 'create_mute'
I don't know where I messed up, must be the installation... Sorry I'm really out of my depth here.

**Comment by Harmon758** [comment]
`API.create_mute` was released with Tweepy 3.7.0, as you can see from the merged commit.
This merged PR isn't the right place to ask for help with using the library.

**Pull request merged**
